---
- hosts: webservers
  become: true
  tasks:
  - name: Installation of packages on Redhat family
    when: ansible_os_family = "Redhat"
    yum: path={{item}} state=present
    with_items:
    - vim
    - zip
    - curl
    - nginx

  - name: Installation of packages on Debain family
    when: ansible_os_family = "Debain"
    apt: path={{item}} state=present
    with_items:
    - vim
    - zip
    - curl
    - nginx

    # Build with custom Dockerfile name
docker build -f Dockerfile -t my-nginx-app .
# List all images
docker images

# Check specific image
docker images my-nginx-app
# Run in foreground
docker run -p 80:80 my-nginx-app

# Run in background (detached mode)
docker run -d -p 80:80 my-nginx-app

# Run with a container name
docker run -d -p 80:80 --name mynginx my-nginx-app
   
