apiVersion: v1
kind: Pod
metadata:
  name: sample-pod-1         # Different name (pods must have unique names)
spec:
  containers:
  - name: nginx-container    # Container 1 - Main app
    image: nginx:latest
    ports:
    - containerPort: 80

  - name: busybox-container  # Container 2 - Sidecar
    image: busybox
    command: ["sleep", "3600"]  # Keeps container alive for 1 hour

    # kubectl apply -f pod.yml
# kubectl get pods
