apiVersion: v1                    # API version for core objects
kind: Service                     # Object type = Service
metadata:
  name: nginx-service-node-port   # Name of the Service
spec:
  selector:
    app: nginxF                   # Routes traffic to pods with this label
  type: NodePort                  # Exposes service on each Node's IP
  ports:
    - port: 80                    # Service port (internal cluster port)
      targetPort: 80              # Container port (nginx listens here)
      nodePort: 30080             # External port on Node (30000-32767)
      protocol: TCP               # Protocol used
# Apply the service
kubectl apply -f nginx-service.yaml

# Check service created
kubectl get service nginx-service-node-port

# Short form
kubectl get svc nginx-service-node-port

# Check all services
kubectl get svc
