apiVersion: v1          # Kubernetes API version for core objects
kind: Pod               # Object type = Pod
metadata:
  name: sample-pod      # Pod name (must be unique in namespace)
spec:
  containers:
  - name: nginx-container    # Container name
    image: nginx:latest      # Docker image pulled from Docker Hub
    ports:
    - containerPort: 80      # Port nginx listens on inside container
    # kubectl apply -f pod.yml
# kubectl get pods

